type:docs:
  - "docs/**/*.md"
area:dependencies:
  - "pnpm-lock.yaml"
  - "yarn.lock"
type:maintenance:
  - "functions/**"
  - "src/**"
  - "lib/**"
  - ".github/CODEOWNERS"
  - ".github/*.md"
  - ".github/*.yml"
  - ".github/*.json"
  - ".vscode"
  - "tsconfig.json"
  - "babel.config.js"
  - "docusaurus.config.js"
  - ".all-contributorsrc"
  - "crowdin.yml"
  - "netlify.toml"
  - ".prettierrc"
  - ".prettierignore"
  - ".markdownlint.json"
  - ".deepsource.toml"
  - ".trunk/*.yaml"
  - ".trunk/*.json"
  - ".trunk/*rc"
area:ci:
  - ".github/workflows/*.yml"
area:plugin:
  - "functions/**"
  - "*.zsh"
area:package:
  - "package.json"
